version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: db/dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goldendarts